version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "angularjs",
    "ember",
    "meteor"
  ]
  environment = [
    "jquery",
    "nodejs",
    "jest",
    "browser",
    "mocha",
    "jasmine"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"