version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  
  plugins = [
    "react",
    "nextjs",
    "node",
    "jest"
  ]
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]

[[analyzers]]
name = "typescript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]

[[analyzers]]
name = "php"

  [analyzers.meta]
  environment = [
    "laravel"
  ]

# (Optional) Enable security and dependency checks
[[transformers]]
name = "prettier"

[[transformers]]
name = "eslint"

[[transformers]]
name = "php-cs-fixer"
